#!/bin/bash

if [ -z "$GIT_EMAIL" ]; then
 echo "You need to pass the \$GIT_EMAIL variable to the container for this to work"
 exit
fi

if [ -z "$GIT_NAME" ]; then
 echo "You need to pass the \$GIT_NAME variable to the container for this to work"
 exit
fi

cd /git
git pull
sed -i "s/config\['site_dir'\]/\"\/var\/www\/html\/\"/g" /git/code/letterpress.py
# chown -Rf nginx:nginx /var/www/html
